In [20]:
import numpy as np
from tensorflow.keras.layers import Embedding

2025-02-16 16:21:39.547576: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2025-02-16 16:21:39.551031: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2025-02-16 16:21:39.551058: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.


In [ ]:
dir = '/home/milad/Desktop/python/AI/DL/Mini_project/db/glove.6B'
embeddings_index = {}
words_to_index = {}
index_to_words = {}
with open(f'{dir}/glove.6B.100d.txt',encoding = 'utf-8') as f:
  lines = f.readlines()
  words = set()
  for line in lines:
    values = line.split()
    word = values[0]
    embed = values[1:]
    weights = np.asarray(embed,dtype = 'float32')
    embeddings_index[word] = weights
    words.add(word)

  i = 1
  for w in sorted(words):
    words_to_index[w] = i
    index_to_words[i] = w
    i += 1

len(embeddings_index.keys())


400000

In [3]:
word = 'sara'
words_to_index[word]

318272

In [4]:
index_to_words[318272]

'sara'

In [7]:
def senetences_to_indices(X,word_to_idx,max_len):
  m = X.shape[0]
  X_indices = np.zeros((m,max_len))
  for i in range(m):
    sentence_words = X[i].lower().split()
    for j,w in enumerate(sentence_words):
      X_indices[i,j] = word_to_idx[w]
  return X_indices

In [19]:
X = np.array(['funny','lets go party','food is ready for you'])
max_sen = np.asarray([len(X[i].split()) for i in range(len(X))]).max()
X_indices = senetences_to_indices(X,words_to_index,max_len = max_sen)
print(X)
print(X_indices)

['funny' 'lets go party' 'food is ready for you']
[[155345.      0.      0.      0.      0.]
 [220930. 163237. 278093.      0.      0.]
 [151204. 192973. 302254. 151349. 394475.]]


In [22]:
def pretrained_embedding_layer(embeddings_index,words_to_index):
  vocab_len = len(words_to_index) + 1 
  emb_dim = embeddings_index['ali'].shape[0]
  emb_matrix = np.zeros((vocab_len,emb_dim))
  for word,index in words_to_index.items():
    emb_matrix[index,:] = embeddings_index[word]
  embedding_layer = Embedding(vocab_len,emb_dim,trainable = False)
  embedding_layer.build((None,))
  embedding_layer.set_weights([emb_matrix])
  return embedding_layer

In [23]:
e = pretrained_embedding_layer(embeddings_index,words_to_index)
e

2025-02-16 16:23:58.618502: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2025-02-16 16:23:58.619745: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2025-02-16 16:23:58.619802: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (milad-HP): /proc/driver/nvidia/version does not exist
2025-02-16 16:23:58.623322: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-02-16 16:23:58.764605: W tensorflow/tsl/framework/cpu_allocator_impl.c