## 1-BinaryCrossentropy

In [5]:
import tensorflow as tf
import numpy as np

In [6]:
binary_cross_entropy=tf.keras.losses.BinaryCrossentropy(from_logits=True)

In [7]:
y = np.array([0,1,0])
preds = np.array([-18 , 0.5 , 3.9])

In [8]:
binary_cross_entropy(y,preds)

<tf.Tensor: shape=(), dtype=float32, numpy=1.4647056>

## 2-CategoricalCrossentropy

In [9]:
from tensorflow.keras.losses import CategoricalCrossentropy

In [10]:
cce=CategoricalCrossentropy()

In [12]:
y=np.array([[0,1,0],[1,0,0]]) # 0 : 0,0,1
pred=np.array([[0.05,0.95,0],[0.1,0.8,0.1]])
cce(y,pred)

<tf.Tensor: shape=(), dtype=float32, numpy=1.1769392>

## 3-SparseCategoricalCrossentropy

In [13]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
scce=SparseCategoricalCrossentropy()

In [15]:
y=np.array([1,2]) # 0 : 0,0,1
pred=np.array([[0.05,0.95,0],[0.1,0.8,0.1]])
scce(y,pred)

<tf.Tensor: shape=(), dtype=float32, numpy=1.1769392>